- name: install ansible dependencies to manage postgresql
  apt:
    pkg: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  with_items:
    - python-psycopg2
    - python-pycurl
    - locales
