- name: install ansible dependencies to manage postgresql
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
    name:
      - python-psycopg2
      - python-pycurl
      - locales
